### ISSUE TITLE
不错

### ISSUE THREAD

**Issue by zxy1994** [rpamis/rpamis-security#1]
这两个功能，都实现过。在公司，写成了两个模块。实现思路还都差不多

- 关于脱敏：当时也是aop做的，针对嵌套这种，其实是换个思路。直接来了个aop套aop的方式，就不需要写递归代码。

- 关于加密：也是用mybatis拦截器做的，不过拦截的部分有点差异，大方向是一致的。

**Comment by benym** [comment]
感谢您的关注❤️，组件要解决的问题是常见的，很多公司内部确实有这类组件，我们的项目主要补充这类项目的开源版本，在保证高质量代码的同时，解决一些细节问题，比如深拷贝，迭代法的嵌套脱敏，动态SQL的加解密，以及代码扩展性等，结合博客解析解答该方向上的一些常见问题😊，也欢迎您提出更好的意见
