### ISSUE TITLE
对手机号加解密没有生效

### ISSUE THREAD

**Issue by 895293122** [rpamis/rpamis-security#2]
![Snipaste_2024-06-17_18-49-02](https://github.com/rpamis/rpamis-security/assets/81350095/4d569914-018d-464d-a91d-e848e189b797)
![Snipaste_2024-06-17_18-49-45](https://github.com/rpamis/rpamis-security/assets/81350095/97e20fb2-e555-4491-9d42-5eb32d2d9b46)
![Snipaste_2024-06-17_18-50-19](https://github.com/rpamis/rpamis-security/assets/81350095/38512119-b4fc-4261-91bd-ac06ef7cf2a5)

**Comment by benym** [comment]
> ![Snipaste_2024-06-17_18-49-02](https://private-user-images.githubusercontent.com/81350095/340279464-4d569914-018d-464d-a91d-e848e189b797.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MjI5MTEsIm5iZiI6MTcxODYyMjYxMSwicGF0aCI6Ii84MTM1MDA5NS8zNDAyNzk0NjQtNGQ1Njk5MTQtMDE4ZC00NjRkLWE5MWQtZTg0OGUxODliNzk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDExMTAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkNTM1MjUyYWNmYTg3ZDNiMGExNjIzYjg2ZTZiMjVkMDBmNjJhZDQ1YzUxMjA2YzA3MjJiMjYzMTVhYTRkNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GJGgGVMa_-mgPGba-o4T_BPuyatDShMTY3ht7oFP2U4) ![Snipaste_2024-06-17_18-49-45](https://private-user-images.githubusercontent.com/81350095/340279632-97e20fb2-e555-4491-9d42-5eb32d2d9b46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MjI5MTEsIm5iZiI6MTcxODYyMjYxMSwicGF0aCI6Ii84MTM1MDA5NS8zNDAyNzk2MzItOTdlMjBmYjItZTU1NS00NDkxLTlkNDItNWViMzJkMmQ5YjQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDExMTAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiYzhhYjRjMjA3MmVlNTZiYWZlY2ViNDY3YTEwZGY3Yzk0MWJiYjNhM2Y2OGY2OWNmZGI1YWMzYTAzMDBjZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OzZcjt7u3jiqC4oWS45HO6DU-9re5jdDqMuRFr4MS6c) ![Snipaste_2024-06-17_18-50-19](https://private-user-images.githubusercontent.com/81350095/340279733-38512119-b4fc-4261-91bd-ac06ef7cf2a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MjI5MTEsIm5iZiI6MTcxODYyMjYxMSwicGF0aCI6Ii84MTM1MDA5NS8zNDAyNzk3MzMtMzg1MTIxMTktYjRmYy00MjYxLTkxYmQtYWMwNmVmN2NmMmE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDExMTAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMDc5ZTNiYjFhODg0MjQ4NGJjZmI0YTNlYzgwZjJlMWFhYTA0NGJiOWFiOTIzNDY0MGJlNjljNWU5M2EzY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.usMINW9rRg_6YU_by0xgT-Mmv6y_LkSah-0xVEXxsuw)

可以给下使用的mapper层写法吗，类似单侧用例中
```java
TestVersionDO testVersionDO = new TestVersionDO();
testVersionDO.setName("张三");
testVersionDO.setIdCard("500101111118181952");
testVersionDO.setPhone("18523578454");
testVersionMapper.insert(testVersionDO);
TestVersionDO selectResult = testVersionMapper.selectById(testVersionDO.getId());
Assert.isTrue("张三".equals(selectResult.getName()), "姓名校验失败");
Assert.isTrue("500101111118181952".equals(selectResult.getIdCard()), "身份证校验失败");
Assert.isTrue("18523578454".equals(selectResult.getPhone()), "电话校验失败");
```
以及实体类是否具有get/set方法？

**Comment by 895293122** [comment]
我是用postman直接传的参数进来, get/set使用的 lombok的@data注解
![Snipaste_2024-06-18_08-41-52](https://github.com/rpamis/rpamis-security/assets/81350095/5a7c2a64-1668-45d0-b8d5-e94186eb6dbb)
![Snipaste_2024-06-18_08-42-01](https://github.com/rpamis/rpamis-security/assets/81350095/c53b799f-caa6-4521-ad83-96be97b47cce)
![Uploading Snipaste_2024-06-18_08-43-09.png…]()

**Comment by 895293122** [comment]
![Snipaste_2024-06-18_08-43-09](https://github.com/rpamis/rpamis-security/assets/81350095/94f85a9d-8714-4734-8776-1f81fa22a9a4)

**Comment by benym** [comment]
> ![Snipaste_2024-06-18_08-43-09](https://private-user-images.githubusercontent.com/81350095/340495444-94f85a9d-8714-4734-8776-1f81fa22a9a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2OTMxMjEsIm5iZiI6MTcxODY5MjgyMSwicGF0aCI6Ii84MTM1MDA5NS8zNDA0OTU0NDQtOTRmODVhOWQtODcxNC00NzM0LTg3NzYtMWY4MWZhMjJhOWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDA2NDAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2MGQyZGE0NDZkODMyNDYxODBkNWNkMjE4NDZhOWJiN2IzZDNhYmI5MTBmNTQ1YzZkM2YyYjdhNGZmMTlmZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sZqExPFuznFnVBXsxvlW1tN6JqbV0umwzEoBS8DjgrM)

我试了下没有复现你说的问题
原始数据如下
![image](https://github.com/rpamis/rpamis-security/assets/38175888/4fecd485-63a6-44c0-8250-08df29192929)
postman传参
![image](https://github.com/rpamis/rpamis-security/assets/38175888/07d554d1-b785-4226-a5da-8a7b01778c93)
执行加密后自动解密正常
![image](https://github.com/rpamis/rpamis-security/assets/38175888/2b28c954-eccd-4889-b746-b9d31f84e584)
数据库正常更新
![image](https://github.com/rpamis/rpamis-security/assets/38175888/c3f907bd-caf7-4fdf-a171-c85c0b053cc1)

你可以确定下你的api接受postman传参时，是否采用了@RequestBody标记入参，解析为json形式
如果你在postman中采用json传递参数，但controller上忘记标识，实际上入参的参数是为null的
除此之外，还可以观察控制台打印的sql参数，看下是否有问题

**Comment by 895293122** [comment]
传参看着没有问题
![Snipaste_2024-06-18_14-58-19](https://github.com/rpamis/rpamis-security/assets/81350095/b90248d9-e905-4e26-95a7-0da366afdacd)
修改之后
![Snipaste_2024-06-18_14-59-31](https://github.com/rpamis/rpamis-security/assets/81350095/8f37092b-a166-4a5c-9050-b8a3a1b8b556)

**Comment by 895293122** [comment]
sql参数是没有改变的
![Snipaste_2024-06-18_15-03-56](https://github.com/rpamis/rpamis-security/assets/81350095/a5193323-c78d-4bc6-a177-ef6f2d3ff9a4)

**Comment by 895293122** [comment]
sql参数是没有改变的
![Snipaste_2024-06-18_15-03-56](https://github.com/rpamis/rpamis-security/assets/81350095/a5193323-c78d-4bc6-a177-ef6f2d3ff9a4)

**Comment by benym** [comment]
提供一下你的Springboot，mybatis or mybatis-plus版本

**Comment by 895293122** [comment]
sprintboot 2.0.3.RELEASE
mybatis 3.4.6

**Comment by benym** [comment]
> sprintboot 2.0.3.RELEASE mybatis 3.4.6

看起来是版本过低导致的问题，这个项目最低支持在SpringBoot 2.3.4.RELEASE-SpringBoot 2.7.18，及mybatis版本3.5.x版本
在单测模块中，通过测试的版本为mybatis 3.5.10
在我们的生产环境，最高支持了SpringBoot2.7.18
低版本的api行为和插件依赖行为有差异，暂时没有往下兼容的计划

你可以选择升级mybatis版本尝试
或者采用手动注入加密算法，自行加密，虽然并不建议这样做
```java
@Resource
private SecurityAlgorithm securityAlgorithm;

TestDO test = new TestDO();
test.setPhone(securityAlgorithm.encrypt("123456789"));
updateMapper.update(test);
```

如果对使用场景有疑问，可以查看对应的单测用例case😊

**Comment by 895293122** [comment]
感谢大佬解惑, 项目确实比较老了。我试下升级版本看能不能解决

**Comment by 895293122** [comment]
感谢大佬!!!
